// SEO Keywords and content strategy
export const SEO_CONFIG = {
  primaryKeywords: [
    'frontend developer',
    'react developer',
    'next.js developer',
    'web developer',
    'freelance frontend developer',
    'UI/UX developer',
  ],
  longTailKeywords: [
    'hire frontend developer',
    'react next.js developer for hire',
    'responsive web design',
    'modern web development',
    'tailwind css developer',
    'web performance optimization',
  ],
  location: 'Hyderabad',
  expertise: [
    'React.js',
    'Next.js',
    'Tailwind CSS',
    'JavaScript',
    'Web Performance',
    'Responsive Design',
    'GSAP Animations',
    'WordPress Development',
  ],
};

export const BLOG_POSTS = [
  {
    id: 'react-best-practices',
    title: 'React Best Practices: Building High-Performance Components',
    slug: 'react-best-practices-high-performance-components',
    excerpt: 'Learn essential React best practices for building fast, maintainable, and scalable applications. Discover optimization techniques, hooks patterns, and performance tips.',
    category: 'React',
    readTime: 8,
    date: '2024-08-20',
    keywords: ['react', 'performance', 'best practices', 'javascript'],
  },
  {
    id: 'nextjs-guide',
    title: 'Complete Next.js Guide: From Basics to Advanced Patterns',
    slug: 'nextjs-guide-basics-advanced-patterns',
    excerpt: 'Master Next.js with this comprehensive guide covering App Router, Server Components, API routes, and advanced patterns for production-ready applications.',
    category: 'Next.js',
    readTime: 12,
    date: '2024-08-15',
    keywords: ['nextjs', 'app router', 'server components', 'web development'],
  },
  {
    id: 'tailwind-css-advanced',
    title: 'Advanced Tailwind CSS: Tips for Building Custom Design Systems',
    slug: 'advanced-tailwind-css-custom-design-systems',
    excerpt: 'Explore advanced Tailwind CSS techniques including custom components, design system creation, and optimization strategies for production.',
    category: 'CSS',
    readTime: 10,
    date: '2024-08-10',
    keywords: ['tailwind css', 'design systems', 'css frameworks', 'ui design'],
  },
  {
    id: 'web-performance',
    title: 'Web Performance Optimization: Speed Up Your React Applications',
    slug: 'web-performance-optimization-react-apps',
    excerpt: 'Comprehensive guide to optimizing React applications for speed and performance. Learn about code splitting, lazy loading, image optimization, and more.',
    category: 'Performance',
    readTime: 14,
    date: '2024-08-05',
    keywords: ['web performance', 'optimization', 'react', 'core web vitals'],
  },
  {
    id: 'responsive-design',
    title: 'Responsive Web Design Best Practices for Modern Devices',
    slug: 'responsive-web-design-best-practices-modern-devices',
    excerpt: 'Learn how to build truly responsive websites that work seamlessly across all devices. Mobile-first approach, media queries, and design tips.',
    category: 'Design',
    readTime: 9,
    date: '2024-07-30',
    keywords: ['responsive design', 'mobile first', 'css', 'web design'],
  },
  {
    id: 'gsap-animations',
    title: 'GSAP Animations: Creating Smooth, Professional Web Animations',
    slug: 'gsap-animations-smooth-professional-web-animations',
    excerpt: 'Master GSAP for creating stunning animations and interactions. Learn timelines, tweens, and best practices for smooth performance.',
    category: 'Animations',
    readTime: 11,
    date: '2024-07-25',
    keywords: ['gsap', 'animations', 'javascript', 'web development'],
  },
];
